INSERT INTO cfrl.food_resources (id, resource_name, resource_owner, description, location_id, contact_id, comments, service_area, documentation_needed, website, day_of_week_offered, delivery_offered, delivery_desc, dietary_considerations, type_id, is_verified) VALUES (1, 'Allied Food Pantry ', null, 'food pantry: We give out pre-packed bags from the outside of the Boys and Girls Club', null, null, null, 'Anyone who lives in the 53711, 53713 or 53719 ZIP code', 'Recipients do not need to sign up in advance but must bring identification for each family member.', 'https://alliedfoodpantry.wixsite.com/allied-food-pantry/who-we-serve', ' Wed 10:00-12:00, and Wed 6:00-7:30 pm', 0, null, null, 1, 1);
INSERT INTO cfrl.food_resources (id, resource_name, resource_owner, description, location_id, contact_id, comments, service_area, documentation_needed, website, day_of_week_offered, delivery_offered, delivery_desc, dietary_considerations, type_id, is_verified) VALUES (3, 'Bethel Food Pantry', null, 'Bethels Food Pantry has been in existence for over 30 years, providing food to those in our community that are food insecure. ', 1, 8889, '', 'n/a', 'Pre-registration is required to use the pantry. Call 608.257.3577 after 9am on the same day you plan to use the pantry.', 'https://www.bethel-madison.org/ministries/serving/bethel-food-pantry/', 'The Pantry is open on Mondays, Wednesdays, and Fridays from 1-3pm. ', 0, '', '', 1, 1);
INSERT INTO cfrl.food_resources (id, resource_name, resource_owner, description, location_id, contact_id, comments, service_area, documentation_needed, website, day_of_week_offered, delivery_offered, delivery_desc, dietary_considerations, type_id, is_verified) VALUES (5, 'The River Food Pantry', 8889, 'The River Food Pantry, serving over 1,000 diverse households each week, is South Central Wisconsins busiest food pantry. Our services include free groceries for curbside pickup or delivery, freshly prepared to-go meals, and mobile lunches for children and adults in low-income neighborhoods. ', 2, 8888, 'If you are not feeling well and need food, we encourage you to stay home. Please email info@riverfoodpantry.org and ask about setting up a proxy shopper.', '', 'All you need to bring is an ID for the head of the household. Youll receive an emailed link to fill out full registration for the full household (here). If you need assistance with the form, give us a call at (608) 442-8815 and we will be happy to pre-register you over the phone. Well ask that you bring in a piece of mail (proof of address) and a form of identification for each household member on your next visit.', 'www.riverfoodpantry.org', 'Tuesday, 10:00am3:00pm, Wednesday	10:00am3:00pm, Thursday,10:00am3:00pm, Friday	10:00am3:00pm', 1, 'To qualify to receive deliveries through River Delivers, you must:

Live in Dane County
Not qualify for established delivery services, such as Dry Hootch or Food Bridge
Not have a form of transportation to The River
Not have a friend, family member or neighbor to transport groceries from The River for you
Have someone home to receive the groceries, as we cannot leave food outside due to maintaining food quality and the possibility of animals getting into the groceries', 'If you have specific dietary needs, please tell one of our volunteers or employees onsite or by emailing info@riverfoodpantry.org. We will do our best to accommodate your needs. Process
Please sign up for delivery as a new delivery client by going to the website.
Requests must be submitted weekly.
', 1, 1);
INSERT INTO cfrl.food_resources (id, resource_name, resource_owner, description, location_id, contact_id, comments, service_area, documentation_needed, website, day_of_week_offered, delivery_offered, delivery_desc, dietary_considerations, type_id, is_verified) VALUES (7, 'Catholic Multicultural Center Food Pantry', 8890, 'Food pantry sign-up and distribution will happen in the CMC parking lot. Each guest may visit up to once a week. ', 3, 8890, 'The Personal Essentials Pantry is pantry is open each Tuesday in conjunction with the food pantry.', '', 'You will be asked to provide your name, birth date, how many people live in your household, and your full address including zip code. ', 'https://cmcmadison.org', 'Tuesday 2:00 to 3:30pm, Thursdays 10:30am to 12:00pm', 0, '', '', 1, 1);
INSERT INTO cfrl.food_resources (id, resource_name, resource_owner, description, location_id, contact_id, comments, service_area, documentation_needed, website, day_of_week_offered, delivery_offered, delivery_desc, dietary_considerations, type_id, is_verified) VALUES (8, 'East Madison Community Center', 8891, 'The East Madison Community Center provides a pre-boxed pantry each Tuesday for families residing in Dane County. Join us every Tuesday from 11:30 am   1:30 pm. for our food pantry.', 4, 8888, 'We provide daily meals to supplement our kids nutrition. Monday through Friday, we serve a healthy snack and dinner during the school year, as well as snack and lunch on Saturdays. In 2017, we served 15,883 meals.', '', 'Food Pantry/TEFAP Application', 'https://eastmadisoncc.org/', 'Tuesday from 11:30 am   1:30 pm. ', 0, '', '', 1, 1);
INSERT INTO cfrl.food_resources (id, resource_name, resource_owner, description, location_id, contact_id, comments, service_area, documentation_needed, website, day_of_week_offered, delivery_offered, delivery_desc, dietary_considerations, type_id, is_verified) VALUES (9, 'Goodman Community Center Fritz Food Pantry', 8892, 'Until the coronavirus is no longer a threat, The Fritz Food Pantry at the Center will distribute food outside in the Ironworks parking lot (149 Waubesa St.) during our regular pantry hours. Both cars and those on foot or bike can be accommodated.&#8203; For the safety of all, masks are required.', 5, 8891, 'The Goodman Community Center offers a variety of programs designed to nourish our community. Our Fritz Food Pantry provides groceries for more than 300 hungry households every week. We are committed to not only alleviating hunger, but also to providing people with healthy foods  fresh, local and organic  as much as we can. ', '', 'No pre-registration is required. Upon arrival you will complete an order form indicating what food you wish to receive.', 'www.goodmancenter.org/services/fritz-food-pantry', 'Tuesday 9:30am  noon, Wednesday 6pm  8pm, Thursday 12:30pm  3pm', 0, '', 'We also try to meet special dietary needs for low-sugar, low-salt and gluten-free foods.', 1, 1);