INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8889, 'pantry', 'volunteer Coordinator', null, '608.257.3577', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8890, 'Catholic Multicultural Center', 'admin', null, '608-661-3512', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8891, '', 'Goodman Community Center', null, '608.241.1574', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8892, 'Pastor Joe', 'Brosious', null, '', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8893, 'dfgd', 'dfg', null, '', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8894, '', 'Pantry', null, '(608) 244-0767', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8895, '', 'Kennedy Heights Food Pantry', null, '(608) 244-0767', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8896, ' ', 'Food Pantry', null, '(608) 244-0767', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8897, '', 'Lakeview Lutheran Church', null, '6082446181', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8898, 'Cristina ', 'Johnson', null, '6088334979', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8899, 'Mariam', 'Sullins', null, '(608) 332-2814', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8900, 'Tony', 'Esser', null, '608-256-8463', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8901, ' Elaine', 'Bogen', null, '608-256-8463', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8902, 'Dick', 'Benzine', null, '6082211241', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8903, '', 'pantry', null, '608-257-0919 ', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8904, '  Eric', 'Salzwedel', null, '', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8905, 'Heather', 'Kurth', null, '6085138769', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8906, ' ', 'office', null, '(608) 848-2499', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8907, ' Heather', 'Kurth', null, '6085138769', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8908, ' ', 'WIC', null, '1-800-722-2295', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8909, ' ', 'The Beacon', null, '608-826-8040', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8910, ' ', 'East Madison Community Center', null, '	(608) 249-0861', null);
INSERT INTO cfrl.contact_details (id, first_name, last_name, email, phone, owner_id) VALUES (8911, ' Nicki', 'Stapleton', 'nicki.stapleton@gmail.com', '', null);