INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (1, 'private or not available', null, null);
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8888, 'default place holder', null, null);
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8889, 'The River Food Pantry', null, 'https://www.riverfoodpantry.org/');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8890, 'Catholic Multicultural Center', null, 'cmcmadison.org');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8891, 'East Madison Community Center', null, 'https://eastmadisoncc.org');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8892, 'Goodman Community Center', null, 'www.goodmancenter.org');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8893, 'cvb', null, '');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8895, 'Kennedy Heights Community Center', null, 'http://www.khcommunitycenter.org/');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8896, 'Lussier Community Education Center', null, 'https://lcecmadison.org/');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8897, 'Meadowood Neighborhood Center', null, 'https://www.mscr.org/meadowood');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8898, 'St. Marks Lutheran Church', null, 'http://stmarksmadison.org');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8899, 'St. Stephan''s Church', null, 'https://www.ststephensmonona.org');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8900, 'St. Vincent de Paul', null, 'https://svdpmadison.org/');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8901, 'Wil-Mar Neighborhood Center', null, 'https://wil-mar.org/about');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8902, 'heather''s org', null, '');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8903, 'sdf', null, '');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8904, 'Badger Prairie Needs Network', null, 'https://www.bpnn.org/');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8905, 'Heather Kurth', null, '');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8906, 'pete something', null, 'cfg.com');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8907, 'USDA', null, 'https://www.fns.usda.gov/');
INSERT INTO cfrl.resource_owners (id, org_name, resource_id, website) VALUES (8908, 'Bashford United Methodist Church', null, 'https://bashfordchurch.org/');