package com.hmkurth.CommunityFoodResources;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;


/**
 * This is the super class model/entity for the Community Food Resources Locator App
 * This will represent an abstract resource which will be extended by  Food Resources and sub classes of food resources.
 * I based the decision to include a superclass for future versions of the app where other types of resources may be added.
 * I am unsure if I am gaining anything by this decision or not.
 *
 * @author hmkurth
 */
public abstract class Resource {
    private final Logger logger = LogManager.getLogger(this.getClass());
    //logger.log("In the abstract class Resource, not sure if I will ever get this message, since it will never be implemented");

    private int resourceId;//autogenerated by db

    private String resourceName;//generic name of resource

    private String resourceOwner;//who owns, what company/church, etc?

    private String resourceDescription;

    private String webLink;

    /**
     * no parameter constructor
     */
    public Resource() {
    }

    @Override
    public String toString() {
        return "Resource{" +
                "logger=" + logger +
                ", resourceId=" + resourceId +
                ", resourceName='" + resourceName + '\'' +
                ", resourceOwner='" + resourceOwner + '\'' +
                ", resourceDescription='" + resourceDescription + '\'' +
                ", webLink='" + webLink + '\'' +
                '}';
    }

    /**
     * Gets resource id.
     *
     * @return the resource id
     */
    public int getResourceId() {
        return resourceId;
    }

    /**
     * Sets resource id.
     *
     * @param resourceId the resource id
     */
    public void setResourceId(int resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * Gets resource name.
     *
     * @return the resource name
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * Sets resource name.
     *
     * @param resourceName the resource name
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * Gets resource owner.
     *
     * @return the resource owner
     */
    public String getResourceOwner() {
        return resourceOwner;
    }

    /**
     * Sets resource owner.
     *
     * @param resourceOwner the resource owner
     */
    public void setResourceOwner(String resourceOwner) {
        this.resourceOwner = resourceOwner;
    }

    /**
     * Gets resource description.
     *
     * @return the resource description
     */
    public String getResourceDescription() {
        return resourceDescription;
    }

    /**
     * Sets resource description.
     *
     * @param resourceDescription the resource description
     */
    public void setResourceDescription(String resourceDescription) {
        this.resourceDescription = resourceDescription;
    }

    /**
     * Gets web link.
     *
     * @return the web link
     */
    public String getWebLink() {
        return webLink;
    }

    /**
     * Sets web link.
     *
     * @param webLink the web link
     */
    public void setWebLink(String webLink) {
        this.webLink = webLink;
    }
}
